<a href="https://colab.research.google.com/github/dhirenk2025cse/fdsexperiments/blob/main/experimentno11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Iris (1) - Iris (1).xlsx - Iris (1) - Iris (1).csv to Iris (1) - Iris (1).xlsx - Iris (1) - Iris (1).csv


In [2]:
import pandas as pd

data = pd.read_csv(list(uploaded.keys())[0])

data.head()

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa


In [3]:
import numpy as np
import pandas as pd

data.info()
print(data['variety'].value_counts())
print(data.head())

x = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42
)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

print(knn.score(x_train, y_train))
print(knn.score(x_test, y_test))

from sklearn.metrics import confusion_matrix, classification_report

prediction = knn.predict(x_test)

print(confusion_matrix(y_test, prediction))
print(classification_report(y_test, prediction))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
0.9642857142857143
0.9736842105263158
[[15  0  0]
 [ 0 10  1]
 [ 0  0 12]]